name = "MSJuliaRegistry"
uuid = "2e0ec2e9-d512-4c27-9171-a609a5f127ac"
repo = "https://github.com/markusschmitt/ms_julia_registry.git"
description = "Private registry - markusschmitt"

[packages]
f439a387-2a26-4d1c-b474-cff597991b60 = { name = "MINE", path = "M/MINE" }
